version: "3.8"

services:
  embedding-service:
    build: .
    ports:
      - "8005:8005"
    environment:
      - EMBEDDING_WORKERS=2
      - TRANSFORMER_MODEL_NAME=sentence-transformers/all-mpnet-base-v2
      - FORCE_CPU=false
      - ENABLE_METRICS=true
      - SENTRY_DSN=
    volumes:
      - .:/app  # Mount current directory for development
    command: >
      poetry run uvicorn embed_endpoint:app 
      --host 0.0.0.0 
      --port 8005 
      --reload  # Enable auto-reload for development

  test:
    build: .
    volumes:
      - .:/app
    command: >
      poetry run pytest tests/ 
      -v 
      --cov=. 
      --cov-report=term-missing
